### PR TITLE
Building python wheels on Github Actions

### PR DESCRIPTION
**Pull request by guilhermebs**
Hello,

I'm a developer of an open-source software that simulates electromagnetic fields for biomedical applications. We are interested in using FMM3D, and to facilitate the installation of the FMM3D Python package, I created some Github Actions which will:

1) Build fmm3dpy as a python wheel in Windows, MacOS and Linux
2) Bundle all external dependencies (e.g. libgfortran)
3) Test the packages

The wheels should be compatible with python ≥ 3.6 in
* Any 64 bit Linux since 2014
* Any MacOS ≥ 10.9 (2013)
* Any recent  64bit Windows

If you are interested, I can also add a section which uploads the wheels to https://pypi.org/. With that in place, users should be able to install it by typing `pip install fmm3dpy`

### CODE REVIEW

**Comment by mrachh** [comment]
Hi,
Thanks a lot for this contribution. It is a great addition to the library. We will be merging these changes into the library shortly. 

If you could add the section which uploads the wheels to pypi.org, then that would be wonderful.

Thanks again.

**Comment by guilhermebs** [comment]
Hi,
Great! Right now I'm on vacation but I will be back to work by the end of the week.
I could make it only upload to pypi if a new tag is pushed, so that you have more control over the releases. Would that be ok with you?

**Comment by guilhermebs** [comment]
Further changes:

- added one additional step to upload wheels to [PyPI](https://pypi.org/project/fmm3dpy/). It is triggered when you push a new tag started with "v" (eg. v1.0). You can do that either using the git command line or github releases.

- changed version number in setup.py to 0.0.1, because I'm not sure you want for this current version to be labeled 1.0 on PyPI

Also, It would be great if one of the main developers made an account in PyPI so that I could transfer ownership of the project.

**Comment by mrachh** [comment]
That's excellent. Thanks a lot. Apologies for the delay in merging the request.

I've created an account on pypi, you can transfer it to username: manasrachh, email: mrachh@flatironinstitute.org

**Comment by guilhermebs** [comment]
I've added you as a project owner. Please feel free to remove or downgrade my permissions, or [create your own API token](https://pypi.org/help/#apitoken) to replace mine in the [repository secrets](https://github.com/flatironinstitute/FMM3D/settings/secrets).

You guys have a great package and have been very quick and open to my suggestions. Thanks a lot!

**Comment by guilhermebs** [comment]
In the last few days I tested the libraries in an older MacOS version (10.14) and several Linux distributions. I found some problems in the binaries which are now fixed.

**Comment by mrachh** [comment]
Apologies for the delay in reply. Thank you very much for your contribution! This has been super helpful! We will be merging it into the main branch shortly. Apologies for the delay in that..

**Comment by guilhermebs** [comment]
No big deal! Thanks a lot for this library, it is really great. We will soon release a new version of our program [SimNIBS](https://github.com/simnibs/simnibs) with FMM features, and it has been working wonderfully.

**Pull request merged**
